import { useState, useEffect } from "react";
import Layout from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";
import { 
  Download, 
  FileText, 
  Calendar,
  Users,
  TrendingUp,
  Filter
} from "lucide-react";

interface SaleData {
  id: string;
  customerName: string;
  quantity: number;
  weight: number;
  pricePerKg: number;
  totalPrice: number;
  date: string;
}

const LaporanPenjualan = () => {
  const { toast } = useToast();
  const [sales, setSales] = useState<SaleData[]>([]);
  const [filteredSales, setFilteredSales] = useState<SaleData[]>([]);
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [customerFilter, setCustomerFilter] = useState("");

  // Load data from localStorage
  useEffect(() => {
    const savedSales = localStorage.getItem('sales');
    if (savedSales) {
      const salesData = JSON.parse(savedSales);
      setSales(salesData);
      setFilteredSales(salesData);
    }
  }, []);

  // Filter sales data
  useEffect(() => {
    let filtered = [...sales];

    // Filter by date range
    if (startDate) {
      filtered = filtered.filter(sale => sale.date >= startDate);
    }
    if (endDate) {
      filtered = filtered.filter(sale => sale.date <= endDate);
    }

    // Filter by customer name
    if (customerFilter) {
      filtered = filtered.filter(sale => 
        sale.customerName.toLowerCase().includes(customerFilter.toLowerCase())
      );
    }

    // Sort by date (newest first)
    filtered.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    setFilteredSales(filtered);
  }, [sales, startDate, endDate, customerFilter]);

  // Format currency
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0,
    }).format(amount);
  };

  // Calculate totals
  const totalQuantity = filteredSales.reduce((sum, sale) => sum + sale.quantity, 0);
  const totalWeight = filteredSales.reduce((sum, sale) => sum + sale.weight, 0);
  const totalRevenue = filteredSales.reduce((sum, sale) => sum + sale.totalPrice, 0);
  const uniqueCustomers = new Set(filteredSales.map(sale => sale.customerName)).size;

  // Export to Excel (CSV format)
  const exportToExcel = () => {
    if (filteredSales.length === 0) {
      toast({
        title: "Tidak ada data",
        description: "Tidak ada data penjualan untuk diekspor",
        variant: "destructive",
      });
      return;
    }

    // Create CSV content with proper formatting
    const headers = [
      'Tanggal',
      'Nama Pelanggan',
      'Jumlah Ekor',
      'Berat Total (Kg)',
      'Harga per Kg (Rp)',
      'Total Harga (Rp)'
    ];

    // Format data rows
    const dataRows = filteredSales.map(sale => [
      new Date(sale.date).toLocaleDateString('id-ID'),
      `"${sale.customerName}"`,
      sale.quantity,
      sale.weight.toFixed(1),
      sale.pricePerKg.toLocaleString('id-ID'),
      sale.totalPrice.toLocaleString('id-ID')
    ]);

    // Create CSV content
    const csvRows = [
      headers.join(','),
      ...dataRows.map(row => row.join(','))
    ];

    // Add summary section
    const summaryRows = [
      '',
      '=== RINGKASAN LAPORAN ===',
      `Total Transaksi,${filteredSales.length}`,
      `Total Pelanggan Unik,${uniqueCustomers}`,
      `Total Ekor Terjual,${totalQuantity}`,
      `Total Berat (Kg),${totalWeight.toFixed(1)}`,
      `Total Pendapatan (Rp),${totalRevenue.toLocaleString('id-ID')}`,
      '',
      `Periode Laporan,${startDate || 'Semua'} s/d ${endDate || 'Semua'}`,
      `Tanggal Export,${new Date().toLocaleDateString('id-ID')} ${new Date().toLocaleTimeString('id-ID')}`,
      '',
      'Generated by Ayam Potong Gacor - Sistem Penjualan'
    ];

    // Combine all content
    const allRows = [...csvRows, ...summaryRows];
    const csvContent = allRows.join('\n');

    // Add BOM for proper UTF-8 encoding in Excel
    const BOM = '\uFEFF';
    const finalContent = BOM + csvContent;

    // Create and download file
    const blob = new Blob([finalContent], { 
      type: 'text/csv;charset=utf-8;' 
    });
    
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    
    // Generate filename with timestamp
    const now = new Date();
    const timestamp = now.toISOString().slice(0, 19).replace(/[T:]/g, '_');
    const dateRange = startDate && endDate 
      ? `_${startDate}_to_${endDate}`
      : startDate 
        ? `_from_${startDate}`
        : endDate 
          ? `_to_${endDate}`
          : '_all_data';
    
    const filename = `Laporan_Penjualan_Ayam_Potong_Gacor${dateRange}_${timestamp}.csv`;
    link.setAttribute('download', filename);
    
    // Trigger download
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    URL.revokeObjectURL(url);

    toast({
      title: "Berhasil Export!",
      description: `File ${filename} berhasil diunduh`,
    });
  };

  // Clear filters
  const clearFilters = () => {
    setStartDate("");
    setEndDate("");
    setCustomerFilter("");
  };

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Laporan Penjualan</h1>
            <p className="text-gray-600 mt-1">Lihat dan unduh laporan penjualan detail</p>
          </div>
          <Button onClick={exportToExcel} className="bg-green-600 hover:bg-green-700">
            <Download className="h-4 w-4 mr-2" />
            Unduh Excel
          </Button>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="bg-gradient-to-br from-blue-50 to-blue-100 border-blue-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-blue-700">Total Transaksi</CardTitle>
              <FileText className="h-4 w-4 text-blue-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-blue-900">{filteredSales.length}</div>
              <p className="text-xs text-blue-600 mt-1">Transaksi penjualan</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-green-50 to-green-100 border-green-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-green-700">Total Pelanggan</CardTitle>
              <Users className="h-4 w-4 text-green-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-900">{uniqueCustomers}</div>
              <p className="text-xs text-green-600 mt-1">Pelanggan unik</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-purple-50 to-purple-100 border-purple-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-purple-700">Total Ekor</CardTitle>
              <TrendingUp className="h-4 w-4 text-purple-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-purple-900">{totalQuantity}</div>
              <p className="text-xs text-purple-600 mt-1">{totalWeight.toFixed(1)} Kg</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-orange-50 to-orange-100 border-orange-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-orange-700">Total Pendapatan</CardTitle>
              <TrendingUp className="h-4 w-4 text-orange-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-orange-900">{formatCurrency(totalRevenue)}</div>
              <p className="text-xs text-orange-600 mt-1">Pendapatan kotor</p>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Filter className="h-5 w-5" />
              Filter Laporan
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <Label htmlFor="start-date">Tanggal Mulai</Label>
                <Input
                  id="start-date"
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                />
              </div>
              <div>
                <Label htmlFor="end-date">Tanggal Akhir</Label>
                <Input
                  id="end-date"
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                />
              </div>
              <div>
                <Label htmlFor="customer-filter">Nama Pelanggan</Label>
                <Input
                  id="customer-filter"
                  placeholder="Cari nama pelanggan..."
                  value={customerFilter}
                  onChange={(e) => setCustomerFilter(e.target.value)}
                />
              </div>
              <div className="flex items-end">
                <Button variant="outline" onClick={clearFilters} className="w-full">
                  Reset Filter
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Sales Table */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Detail Penjualan
              </span>
              <Badge variant="outline">
                {filteredSales.length} dari {sales.length} transaksi
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            {filteredSales.length > 0 ? (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Tanggal</TableHead>
                      <TableHead>Nama Pelanggan</TableHead>
                      <TableHead className="text-right">Jumlah Ekor</TableHead>
                      <TableHead className="text-right">Berat (Kg)</TableHead>
                      <TableHead className="text-right">Harga/Kg</TableHead>
                      <TableHead className="text-right">Total Harga</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredSales.map((sale) => (
                      <TableRow key={sale.id}>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Calendar className="h-4 w-4 text-gray-400" />
                            {new Date(sale.date).toLocaleDateString('id-ID')}
                          </div>
                        </TableCell>
                        <TableCell className="font-medium">{sale.customerName}</TableCell>
                        <TableCell className="text-right">{sale.quantity} ekor</TableCell>
                        <TableCell className="text-right">{sale.weight} Kg</TableCell>
                        <TableCell className="text-right">{formatCurrency(sale.pricePerKg)}</TableCell>
                        <TableCell className="text-right font-medium text-green-600">
                          {formatCurrency(sale.totalPrice)}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>

                {/* Summary Row */}
                <div className="border-t mt-4 pt-4">
                  <div className="grid grid-cols-6 gap-4 text-sm font-medium">
                    <div className="col-span-2 text-gray-700">TOTAL</div>
                    <div className="text-right text-gray-700">{totalQuantity} ekor</div>
                    <div className="text-right text-gray-700">{totalWeight.toFixed(1)} Kg</div>
                    <div className="text-right text-gray-700">-</div>
                    <div className="text-right text-green-600 font-bold">
                      {formatCurrency(totalRevenue)}
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center py-8">
                <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                <p className="text-gray-500 text-lg">Tidak ada data penjualan</p>
                <p className="text-gray-400 text-sm mt-1">
                  {sales.length === 0 
                    ? "Belum ada transaksi penjualan yang tercatat"
                    : "Tidak ada data yang sesuai dengan filter yang dipilih"
                  }
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
};

export default LaporanPenjualan;