import { useState, useEffect } from "react";
import Layout from "@/components/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SaleData, TABLE_NAMES } from "@/types/database";
import { 
  Download, 
  FileText, 
  Calendar,
  Users,
  TrendingUp,
  Filter,
  Loader2,
  Printer,
  Edit,
  Wallet,
  CheckCircle2,
  XCircle,
  Clock
} from "lucide-react";

interface ExtendedSaleData extends SaleData {
  payment_status?: string;
  amount_paid?: number;
  product_type?: string;
}

const LaporanPenjualan = () => {
  const { toast } = useToast();
  const [sales, setSales] = useState<ExtendedSaleData[]>([]);
  const [filteredSales, setFilteredSales] = useState<ExtendedSaleData[]>([]);
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [customerFilter, setCustomerFilter] = useState("");
  const [loading, setLoading] = useState(true);

  // States untuk Update Pembayaran
  const [selectedSale, setSelectedSale] = useState<ExtendedSaleData | null>(null);
  const [inputPayment, setInputPayment] = useState(""); 
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [updateLoading, setUpdateLoading] = useState(false);

  // --- LOAD DATA ---
  const loadSales = async () => {
    try {
      setLoading(true);
      const { data: salesData, error } = await supabase
        .from(TABLE_NAMES.SALES)
        .select('*')
        .order('date', { ascending: false });
      
      if (error) throw error;
      
      setSales(salesData || []);
      setFilteredSales(salesData || []);
    } catch (error) {
      console.error('Error:', error);
      toast({ title: "Error", description: "Gagal memuat data", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSales();
  }, []);

  // --- FILTER LOGIC ---
  useEffect(() => {
    let filtered = [...sales];
    if (startDate) filtered = filtered.filter(sale => sale.date >= startDate);
    if (endDate) filtered = filtered.filter(sale => sale.date <= endDate);
    if (customerFilter) {
      filtered = filtered.filter(sale => 
        sale.customer_name.toLowerCase().includes(customerFilter.toLowerCase())
      );
    }
    filtered.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    setFilteredSales(filtered);
  }, [sales, startDate, endDate, customerFilter]);

  // --- CALCULATIONS (Untuk Summary Cards) ---
  const totalQuantity = filteredSales.reduce((sum, sale) => sum + sale.quantity, 0);
  const totalWeight = filteredSales.reduce((sum, sale) => sum + sale.weight, 0);
  const totalRevenue = filteredSales.reduce((sum, sale) => sum + sale.total_price, 0);
  const uniqueCustomers = new Set(filteredSales.map(sale => sale.customer_name)).size;

  // --- EXPORT TO EXCEL (Fitur Abang + Update Kolom Baru) ---
  const exportToExcel = () => {
    if (filteredSales.length === 0) return toast({ title: "Kosong", description: "Tidak ada data untuk diekspor", variant: "destructive" });

    const headers = [
      'Tanggal',
      'Nama Pelanggan',
      'Jenis Produk',
      'Jumlah Ekor',
      'Berat Total (Kg)',
      'Total Tagihan (Rp)',
      'Sudah Bayar (Rp)',
      'Sisa Hutang (Rp)',
      'Status'
    ];

    const dataRows = filteredSales.map(sale => {
      const bayar = sale.amount_paid || 0;
      const sisa = Math.max(0, sale.total_price - bayar);
      return [
        new Date(sale.date).toLocaleDateString('id-ID'),
        `"${sale.customer_name}"`,
        `"${sale.product_type || '-'}"`,
        sale.quantity,
        sale.weight.toFixed(1),
        sale.total_price,
        bayar,
        sisa,
        `"${sale.payment_status || 'Belum Lunas'}"`
      ];
    });

    const csvRows = [
      headers.join(','),
      ...dataRows.map(row => row.join(','))
    ];

    // Add Summary at bottom
    const summaryRows = [
      '', '', '', '', '', '', '', '', '',
      '=== RINGKASAN ===',
      `Total Transaksi,${filteredSales.length}`,
      `Total Pendapatan,${totalRevenue}`,
      `Generated by Ayam Potong Gacor`
    ];

    const csvContent = '\uFEFF' + [...csvRows, ...summaryRows].join('\n'); // Add BOM
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `Laporan_Gacor_${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast({ title: "Berhasil Export!", description: "File Excel berhasil diunduh" });
  };

  // --- UPDATE PAYMENT LOGIC ---
  const handleUpdatePayment = async () => {
    if (!selectedSale) return;
    setUpdateLoading(true);

    try {
      const bayar = parseInt(inputPayment.replace(/\D/g, '')) || 0;
      const totalTagihan = selectedSale.total_price;
      
      let statusOtomatis = "Belum Lunas";
      if (bayar >= totalTagihan) statusOtomatis = "Lunas";

      const { error } = await supabase
        .from(TABLE_NAMES.SALES)
        .update({ 
          payment_status: statusOtomatis,
          amount_paid: bayar 
        })
        .eq('id', selectedSale.id);

      if (error) throw error;

      toast({ title: "Pembayaran Disimpan", description: `Status sekarang: ${statusOtomatis}` });
      setIsDialogOpen(false);
      loadSales(); 
    } catch (error) {
      toast({ title: "Error", description: "Gagal update pembayaran", variant: "destructive" });
    } finally {
      setUpdateLoading(false);
    }
  };

  // --- PRINT RECEIPT ---
  const handlePrint = (sale: ExtendedSaleData) => {
    const bayar = sale.amount_paid || 0;
    const sisa = bayar - sale.total_price;
    const statusText = sisa >= 0 ? "KEMBALI" : "SISA HUTANG";

    const receiptContent = `
      <html>
        <head>
          <title>Resi Transaksi</title>
          <style>
            body { font-family: 'Courier New', monospace; font-size: 12px; width: 100%; margin: 0; padding: 10px; }
            .container { max-width: 300px; margin: 0 auto; }
            .header { text-align: center; margin-bottom: 10px; }
            .title { font-size: 16px; font-weight: bold; }
            .divider { border-top: 1px dashed #000; margin: 8px 0; }
            .row { display: flex; justify-content: space-between; margin-bottom: 4px; }
            .total-row { font-weight: bold; font-size: 14px; margin-top: 5px; }
            .footer { text-align: center; margin-top: 15px; font-size: 10px; }
            .status-box { border: 1px solid #000; padding: 2px 5px; display: inline-block; margin-top: 5px; font-weight:bold; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <div class="title">AYAM POTONG GACOR</div>
              <div>Jalan Pesantren No. 1</div>
            </div>
            <div class="divider"></div>
            <div class="row">
              <span>Tgl: ${new Date(sale.date).toLocaleDateString('id-ID')}</span>
              <span>${new Date().toLocaleTimeString('id-ID', {hour: '2-digit', minute:'2-digit'})}</span>
            </div>
            <div class="row"><span>Plg: ${sale.customer_name}</span></div>
            <div class="divider"></div>
            <div class="row"><span>${sale.product_type || 'Ayam'}</span></div>
            <div class="row">
              <span>${sale.quantity} Ekor x ${formatCurrency(sale.price_per_kg)}</span>
              <span>${sale.weight} Kg</span>
            </div>
            <div class="divider"></div>
            <div class="row total-row">
              <span>TOTAL</span>
              <span>${formatCurrency(sale.total_price)}</span>
            </div>
            <div class="row">
              <span>BAYAR</span>
              <span>${formatCurrency(bayar)}</span>
            </div>
            <div class="row">
              <span>${statusText}</span>
              <span>${formatCurrency(Math.abs(sisa))}</span>
            </div>
            <div class="header"><div class="status-box">${sale.payment_status || 'BELUM LUNAS'}</div></div>
            <div class="footer"><p>Terima Kasih!</p></div>
          </div>
          <script>window.onload = function() { window.print(); }</script>
        </body>
      </html>
    `;
    const printWindow = window.open('', '', 'width=350,height=500');
    if (printWindow) {
      printWindow.document.write(receiptContent);
      printWindow.document.close();
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount);
  };

  const getStatusColor = (status: string) => {
    if (status === 'Lunas') return "bg-green-100 text-green-700 border-green-200";
    return "bg-red-100 text-red-700 border-red-200";
  };

  return (
    <Layout>
      <div className="space-y-6 pb-20">
        
        {/* HEADER & EXPORT */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Laporan Penjualan</h1>
            <p className="text-gray-600 mt-1">Kelola pembayaran, cetak resi, dan riwayat transaksi</p>
            {loading && <div className="flex items-center gap-2 text-sm text-gray-500 mt-2"><Loader2 className="h-4 w-4 animate-spin"/> Memuat data...</div>}
          </div>
          <Button onClick={exportToExcel} className="bg-green-600 hover:bg-green-700 w-full md:w-auto">
            <Download className="h-4 w-4 mr-2" /> Unduh Excel
          </Button>
        </div>

        {/* SUMMARY CARDS (Fitur Abang yang Colorful) */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="bg-gradient-to-br from-blue-50 to-blue-100 border-blue-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-blue-700">Total Transaksi</CardTitle>
              <FileText className="h-4 w-4 text-blue-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-blue-900">{filteredSales.length}</div>
              <p className="text-xs text-blue-600 mt-1">Transaksi penjualan</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-green-50 to-green-100 border-green-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-green-700">Total Pelanggan</CardTitle>
              <Users className="h-4 w-4 text-green-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-900">{uniqueCustomers}</div>
              <p className="text-xs text-green-600 mt-1">Pelanggan unik</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-purple-50 to-purple-100 border-purple-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-purple-700">Total Ekor</CardTitle>
              <TrendingUp className="h-4 w-4 text-purple-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-purple-900">{totalQuantity}</div>
              <p className="text-xs text-purple-600 mt-1">{totalWeight.toFixed(1)} Kg</p>
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-orange-50 to-orange-100 border-orange-200">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-orange-700">Total Pendapatan</CardTitle>
              <TrendingUp className="h-4 w-4 text-orange-600" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-orange-900">{formatCurrency(totalRevenue)}</div>
              <p className="text-xs text-orange-600 mt-1">Pendapatan kotor</p>
            </CardContent>
          </Card>
        </div>

        {/* FILTERS */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Filter className="h-4 w-4" /> Filter Laporan
            </CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-4 gap-3">
            <div><Label>Mulai</Label><Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></div>
            <div><Label>Sampai</Label><Input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} /></div>
            <div><Label>Nama</Label><Input placeholder="Cari pelanggan..." value={customerFilter} onChange={(e) => setCustomerFilter(e.target.value)} /></div>
            <div className="flex items-end"><Button variant="outline" onClick={() => {setStartDate(""); setEndDate(""); setCustomerFilter("")}} className="w-full">Reset</Button></div>
          </CardContent>
        </Card>

        {/* --- TAMPILAN MOBILE (CARD VIEW) --- */}
        <div className="md:hidden space-y-3">
          {filteredSales.map((sale) => (
            <Card key={sale.id} className="border shadow-sm">
              <CardContent className="p-4">
                <div className="flex justify-between items-start mb-3">
                  <div>
                    <h3 className="font-bold text-gray-900">{sale.customer_name}</h3>
                    <div className="text-xs text-gray-500 flex items-center gap-1">
                      <Calendar className="h-3 w-3" /> {new Date(sale.date).toLocaleDateString('id-ID')}
                    </div>
                  </div>
                  <Badge variant="outline" className={getStatusColor(sale.payment_status || 'Belum Lunas')}>
                    {sale.payment_status || 'Belum Lunas'}
                  </Badge>
                </div>
                
                <div className="grid grid-cols-2 gap-2 text-sm mb-3 bg-gray-50 p-2 rounded">
                  <div>
                    <p className="text-gray-500 text-xs">Produk</p>
                    <p className="font-medium">{sale.product_type} ({sale.quantity})</p>
                  </div>
                  <div className="text-right">
                    <p className="text-gray-500 text-xs">Tagihan</p>
                    <p className="font-bold text-gray-900">{formatCurrency(sale.total_price)}</p>
                  </div>
                </div>

                <div className="flex justify-between items-center pt-2 border-t">
                  <div className="text-xs">
                    <p className="text-gray-500">Bayar:</p>
                    <p className={`font-semibold ${(sale.amount_paid || 0) < sale.total_price ? 'text-red-600' : 'text-green-600'}`}>
                      {formatCurrency(sale.amount_paid || 0)}
                    </p>
                  </div>
                  <div className="flex gap-2">
                     <Button size="icon" variant="outline" className="h-8 w-8" onClick={() => handlePrint(sale)}>
                        <Printer className="h-4 w-4" />
                     </Button>
                     <Button size="sm" className="bg-blue-600 h-8 text-xs" onClick={() => {
                        setSelectedSale(sale);
                        setInputPayment((sale.amount_paid || 0).toString());
                        setIsDialogOpen(true);
                     }}>
                        <Wallet className="h-3 w-3 mr-1" /> Bayar
                     </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* --- TAMPILAN DESKTOP (TABLE VIEW) --- */}
        <Card className="hidden md:block">
          <CardHeader>
            <CardTitle className="text-lg">Detail Transaksi</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Tanggal</TableHead>
                  <TableHead>Pelanggan</TableHead>
                  <TableHead>Produk</TableHead>
                  <TableHead className="text-right">Tagihan</TableHead>
                  <TableHead className="text-right">Sudah Bayar</TableHead>
                  <TableHead className="text-right">Sisa Hutang</TableHead>
                  <TableHead className="text-center">Status</TableHead>
                  <TableHead className="text-center">Aksi</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredSales.map((sale) => {
                  const sisa = Math.max(0, sale.total_price - (sale.amount_paid || 0));
                  return (
                    <TableRow key={sale.id}>
                      <TableCell>{new Date(sale.date).toLocaleDateString('id-ID')}</TableCell>
                      <TableCell className="font-medium">{sale.customer_name}</TableCell>
                      <TableCell>{sale.product_type} <span className="text-xs text-gray-400">({sale.quantity} Ekor)</span></TableCell>
                      <TableCell className="text-right font-bold">{formatCurrency(sale.total_price)}</TableCell>
                      <TableCell className="text-right text-green-600">{formatCurrency(sale.amount_paid || 0)}</TableCell>
                      <TableCell className="text-right text-red-600 font-medium">{sisa > 0 ? formatCurrency(sisa) : '-'}</TableCell>
                      <TableCell className="text-center">
                        <Badge variant="outline" className={getStatusColor(sale.payment_status || 'Belum Lunas')}>
                          {sale.payment_status || 'Belum Lunas'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-center">
                        <div className="flex justify-center gap-2">
                          <Button size="icon" variant="ghost" onClick={() => handlePrint(sale)}>
                            <Printer className="h-4 w-4 text-gray-500" />
                          </Button>
                          <Button size="sm" variant="outline" onClick={() => {
                            setSelectedSale(sale);
                            setInputPayment((sale.amount_paid || 0).toString());
                            setIsDialogOpen(true);
                          }}>
                            <Edit className="h-4 w-4 mr-1" /> Atur
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* DIALOG UPDATE PEMBAYARAN */}
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>Update Pembayaran</DialogTitle>
              <p className="text-sm text-gray-500">Pelanggan: {selectedSale?.customer_name}</p>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="p-3 bg-gray-50 rounded-lg space-y-2">
                <div className="flex justify-between text-sm">
                   <span>Total Tagihan:</span>
                   <span className="font-bold">{selectedSale && formatCurrency(selectedSale.total_price)}</span>
                </div>
                <div className="flex justify-between text-sm text-green-600">
                   <span>Sudah Masuk:</span>
                   <span>{selectedSale && formatCurrency(selectedSale.amount_paid || 0)}</span>
                </div>
              </div>
              <div className="space-y-2">
                <Label>Nominal Uang Diterima (Total)</Label>
                <div className="relative">
                  <span className="absolute left-3 top-2.5 text-gray-500">Rp</span>
                  <Input 
                    type="number" 
                    className="pl-10 text-lg font-semibold"
                    value={inputPayment}
                    onChange={(e) => setInputPayment(e.target.value)}
                    placeholder="0"
                  />
                </div>
                <p className="text-xs text-gray-500">*Masukkan total uang yang sudah diterima dari awal.</p>
              </div>
              {selectedSale && inputPayment && (
                 <div className="text-right text-sm">
                    Sisa Hutang / Kembalian: <br/>
                    <span className={`font-bold text-lg ${
                       (parseInt(inputPayment) - selectedSale.total_price) >= 0 ? 'text-green-600' : 'text-red-600'
                    }`}>
                       {formatCurrency(parseInt(inputPayment) - selectedSale.total_price)}
                    </span>
                 </div>
              )}
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsDialogOpen(false)}>Batal</Button>
              <Button onClick={handleUpdatePayment} disabled={updateLoading} className="bg-blue-600">
                {updateLoading ? <Loader2 className="h-4 w-4 animate-spin"/> : "Simpan Pembayaran"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </Layout>
  );
};

export default LaporanPenjualan;
